# Generated by Django 3.1.1 on 2023-07-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20230718_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='empaddress',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
