# Generated by Django 3.1.1 on 2023-07-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeedetail_empaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='empaddress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
