# Generated by Django 3.1.1 on 2023-07-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeeeducation_employeeexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='empjoiningdate',
            new_name='empjoinningdate',
        ),
    ]
