# Generated by Django 3.1.1 on 2023-07-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20230722_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='couressc',
            new_name='coursessc',
        ),
    ]
