# Generated by Django 3.1.1 on 2023-07-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20230722_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='empaddress',
            new_name='address',
        ),
    ]
